DROP table Case_ IF exists;

create table Case_ (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	case_solnUsed_Name VARCHAR(100),
	
	case_isListedBuilding BOOLEAN,
	case_isOccupiedBuilding BOOLEAN,
	case_hasExposedArt BOOLEAN,
	
	case_geoTempMax INT,
	case_geoTempMin INT,
	case_geoHumidityPercentage INT,
	
	case_structArea_cat VARCHAR(100),
	case_structArea_type VARCHAR(100),
	case_structArea_isExposed BOOLEAN,
	
	case_dmgComponent_name VARCHAR(100),
	case_dmgComponent_locn VARCHAR(100),
	case_dmgComponent_structPurp VARCHAR(100),
	case_dmgComponent_materialGrade VARCHAR(100),
	case_dmgComponent_csArea INT,
	case_dmgComponent_csSpan INT,
	case_dmgComponent_dmgPercentage INT,
	
	PRIMARY KEY (id)
);