DROP table Case_ IF exists;

create table Case_ (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	solnName VARCHAR(100) NOT NULL,
	tempMax INT,
	tempMin INT,
	humidityAv INT,
	roofType INT,
	damagePercent INT,
	PRIMARY KEY (id)
);